### ISSUE TITLE
Docker Install

### ISSUE THREAD

**Issue by tucker19** [Sebazzz/PokerTime#193]
With a Docker install do I still need a json or ini file to add environment variables? Is it possible to build in env variables that Docker uses or add a settings GUI within the app?

**Comment by Sebazzz** [comment]
With docker you can either redirect the configuration directory or add the environment variables in the docker run configuration (or docker-compose.yaml)

Met vriendelijke groet,
Sebastiaan Dammann
________________________________
Van: Adam Howell ***@***.***>
Verzonden: Monday, October 4, 2021 6:07:58 PM
Aan: Sebazzz/PokerTime ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [Sebazzz/PokerTime] Docker Install (#193)


With a Docker install do I still need a json or ini file to add environment variables? Is it possible to build in env variables that Docker uses or add a settings GUI within the app?

**Comment by tucker19** [comment]
Thank you.
